name: CheckIn

on:
  schedule:
    - cron: "0 16 * * *" # 北京时间上午00:00
  workflow_dispatch:
jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        env:
          COOKIE_0: ${{ secrets.COOKIE_0 }}
          COOKIE_1: ${{ secrets.COOKIE_1 }}
          COOKIE_2: ${{ secrets.COOKIE_2 }}
          COOKIE_3: ${{ secrets.COOKIE_3 }}
          COOKIE_4: ${{ secrets.COOKIE_4 }}
          COOKIE_5: ${{ secrets.COOKIE_5 }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: |
          npm run dev
